# Generated by Django 5.0.2 on 2024-03-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_verdura_rename_verduleria_fruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='unidad',
            field=models.IntegerField(),
        ),
    ]
